/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "CrossWhisper"
include(":CrossWhisperModels")
include(":CrossWhipserBukkit")
include(":CrossWhisperBungee")
project(":CrossWhisperModels").projectDir = file("models")
project(":CrossWhipserBukkit").projectDir = file("bukkit")
project(":CrossWhisperBungee").projectDir = file("bungee")
