/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.minevn.java-conventions")
}

dependencies {
    api(project(":CrossWhisperModels"))
    compileOnly("org.spigotmc:spigot-api:1.12.2-R0.1-SNAPSHOT")
}

description = "CrossWhipserBukkit"
