/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.minevn.java-conventions")
}

dependencies {
    api(project(":CrossWhisperModels"))
    compileOnly("net.md-5:bungeecord-api:1.18-R0.1-SNAPSHOT")
}

description = "CrossWhisperBungee"
